### ISSUE TITLE
Haus.html

### ISSUE THREAD

**Issue by mrbutcher93** [muting/TGZ-Website#1]
Die Seite Haus.html ist obwohl der Link auf der Seite nicht mehr aktiv ist, immer noch über die URL aufrufbar

**Comment by Puggingtons** [comment]
Inwiefern ist das problematisch?

**Comment by mrbutcher93** [comment]
Wurde doch wegen Datenschutz und Trennung vom Verein rausgenommen

**Comment by Puggingtons** [comment]
ah ok alles klar. Wird rausgenommen
