### ISSUE TITLE
Wen wir suchen

### ISSUE THREAD

**Issue by mrbutcher93** [muting/TGZ-Website#11]
![grafik](https://user-images.githubusercontent.com/46487140/79579931-8c119b00-80c8-11ea-83c4-0f2e4bd1f81e.png)

Hier fehlt doch irgendwie ein Teil des Texts?
Doppelpunkt und dann kommt nichts

**Comment by muting** [comment]
Das Zitat ist wohl beim Transfer verloren gegangen, habs wieder ergänzt
