### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by mrbutcher93** [muting/TGZ-Website#16]
Ich mal wieder :sweat_smile:

![grafik](https://user-images.githubusercontent.com/46487140/80242908-753dec00-8666-11ea-8f93-3cab966b1d36.png)

Meinst du es geht, einen Link zu Google Maps wie im nachfolgenden Bild, hinzuzufügen?
![grafik](https://user-images.githubusercontent.com/46487140/80242938-84bd3500-8666-11ea-9f9a-4519bf571b48.png)

**Comment by muting** [comment]
Das wäre definitiv eine Verbesserung! Ich recherchiere mal, ob es mit der einfachen HTML Einbindung wie wirs haben geht😁

**Comment by mrbutcher93** [comment]
Ich glaub das einfachste wäre die URL in den Infowindow content mit rein zu schreiben. Ich probiere es später mal aus
