### ISSUE TITLE
Umzug auf gitlab.com

### ISSUE THREAD

**Issue by mrbutcher93** [muting/TGZ-Website#24]
Ich habe das repository auf https://gitlab.com/t_gotia-zaringia/tgz_website umgezogen, damit jeglicher code in Bezug zur TGZ an einem Ort ist. Die Gruppe selbst ist öffentlich, alle Projekte in der Gruppe sind aber privat.

@Puggingtons & @muting: Sagt was ihr davon haltet, und fragt am besten Zugriff zur Gitlab-Gruppe an.

**Comment by mrbutcher93** [comment]
@muting bitte archivier das repo hier dann. Dann gibt's keine Dopplungen.

**Comment by muting** [comment]
Done
