### ISSUE TITLE
Email-Adresse vor Spam schützen

### ISSUE THREAD

**Issue by mrbutcher93** [muting/TGZ-Website#8]
Ist das wirklich erledigt? Im Impressum ist die Email zwar nicht klickbar aber ich glaube auch nciht sonderlich vor Spam geschützt.

_Originally posted by @mrbutcher93 in https://github.com/muting/TGZ-Website/issues/4#issuecomment-615083826_

**Comment by muting** [comment]
Nummer und Mails werden mit Zusatztexte verschleiert, sodass Skimming bereits verhindert werden sollten.
