### ISSUE TITLE
Nextcloud-Calendar einbinden

### ISSUE THREAD

**Issue by mrbutcher93** [muting/TGZ-Website#9]
Wenn alles glatt geht werden wir demnächst offiziell von der Dropbox auf die Nextcloud umsteigen. Dadurch gibt es die Möglichkeit den Nextcloud Kalender mit dem Semesterprogramm zu füllen und auf die Homepage zu stellen.
Könnte man sich überlegen statt der SemPro PDF oder als Ergänzung. Vorteil ist, man kann ihn super einfach dem Handy oder Outlook hinzufügen.

Link zum Kalender:
https://nextcloud.gotia-zaringia.de/index.php/apps/calendar/p/BYoQDq2T9yea4rSy

Zum einbetten:
<iframe width="400" height="215" src="https://nextcloud.gotia-zaringia.de/index.php/apps/calendar/p/BYoQDq2T9yea4rSy"></iframe>

**Comment by muting** [comment]
Habe es erstmal als Ergänzung unter dem SemPro eingebettet. 
Die Issue wird erstmal offen gelassen, um evt. Weiterentwicklung zu tracken.

**Comment by mrbutcher93** [comment]
> 
> 
> Wenn alles glatt geht werden wir demnächst offiziell von der Dropbox auf die Nextcloud umsteigen. Dadurch gibt es die Möglichkeit den Nextcloud Kalender mit dem Semesterprogramm zu füllen und auf die Homepage zu stellen.
> Könnte man sich überlegen statt der SemPro PDF oder als Ergänzung. Vorteil ist, man kann ihn super einfach dem Handy oder Outlook hinzufügen.
> 
> Link zum Kalender:
> https://nextcloud.gotia-zaringia.de/index.php/apps/calendar/p/BYoQDq2T9yea4rSy
> 
> Zum einbetten:
> <iframe width="400" height="215" src="https://nextcloud.gotia-zaringia.de/index.php/apps/calendar/p/BYoQDq2T9yea4rSy"></iframe>

EDIT: Link der Nextcloud geändert.

**Comment by mrbutcher93** [comment]
Ist glaub ich noch nicht aktualisiert hochgeladen oder?
